version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: takehome-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: application
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
