version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: takehome-postgres
    restart: on-failure
    profiles: ['dev', 'app']
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: application
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  api:
    build: .
    container_name: takehome-api
    restart: on-failure
    profiles: ['app']
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://application:password@postgres:5432/postgres?schema=public
      SERVER_URL: http://localhost:8080
    ports:
      - 8080:8080
