components:
  schemas:
    Link:
      properties:
        id:
          type: string
          description: link ID.
          example: clk39pduw0002yyinboss60b2
        slug:
          type: string
          description: link's slug.
          example: pxee0kr3n
        original:
          type: string
          description: link's original url.
          example: https://redhotchilipeppers.com/
        shortened:
          type: string
          description: link's shortened url.
          example: http://localhost:8080/pxee0kr3n
        redirects:
          type: integer
          description: number of times the shortened link has redirected.
          example: 7
        cursor:
          type: integer
          description: cursor used for pagination
          example: 11
        createdAt:
          type: date-time
          description: time the link was created
          example: 2023-07-15T00:28:24.033Z
        updatedAt:
          type: date-time
          description: last time the link was updated
          example: 2023-07-15T00:28:29.885Z
    BadRequest:
      properties:
        code:
          type: string
          example: invalid_string
        message:
          type: string
          example: Invalid url
        path:
          type: array
          items:
            type: string
            example: url
